---
AWSTemplateFormatVersion: '2010-09-09'
Description: Provisioning environment

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Global Configuration
        Parameters:
          - AppName
      - Label:
          default: Network setup
        Parameters:
          - CreateNewVPC
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
      - Label:
          default: ECS Cluster setup
        Parameters:
          - ECSInstanceType
          - ECSDesiredClusterSize
          - ECSMaxClusterSize
          - ECSKeyPair
      - Label:
          default: Bastion host setup
        Parameters:
          - BastionInstanceType
          - BastionRemoteAccessCIDR
          - BastionKeyPair
          - DesiredNumBastionHosts
          - MaxNumBastionHosts
      - Label:
          default: RDS host setup
        Parameters:
          - DBName
          - DBUser
          - DBPassword
          - RDSGbStorage
          - DBInstanceClass
          - RDSMultiAZ

    ParameterLabels:
      AppName:
        default: Name of App/Org
      VpcCidr:
        default: VPC CIDR
      PublicSubnet1CIDR:
        default: Public Subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public Subnet 2 CIDR
      PrivateSubnet1CIDR:
        default: Private Subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private Subnet 2 CIDR

Parameters:
  # 01-stack-set
  CreateRdsInstance: 
    Description: Create RDS Instance?
    Default: true
    Type: String
    AllowedValues: [true, false]
    ConstraintDescription: Create new RDS
  AppName: 
    Type: String
    Default: test-app-dev
    Description: Name of your application or organization
  VpcCIDR: 
    Type: String
    Default: 10.0.0.0/16
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))?$"
    Description: Enter VPC IP range (CIDR)  x.x.x.x/y (x=1 to 255, y=1 to 32)
  PublicSubnet1CIDR:
    Type: String
    Default: 10.0.10.0/24
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))?$"
    Description: Enter Subnet IP range (CIDR) for the public subnet in the first Availability Zone
  PublicSubnet2CIDR:
    Type: String
    Default: 10.0.20.0/24
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))?$"
    Description: Enter Subnet IP range (CIDR) for the public subnet in the second Availability Zone
  PrivateSubnet1CIDR:
    Type: String
    Default: 10.0.11.0/24
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))?$"
    Description: Enter Subnet IP range (CIDR) for the private subnet in the first Availability Zone
  PrivateSubnet2CIDR:
    Type: String
    Default: 10.0.21.0/24
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))?$"
    Description: Enter Subnet IP range (CIDR) for the private subnet in the second Availability Zone
  # 02-create-ecs-cluster
  ECSInstanceType:
    Description: EC2 instance type
    Type: String
    Default: t2.micro
    AllowedValues: [t3.micro, t3.small, t3.medium, t3.large, t2.micro, t2.small,
      t2.medium, t2.large, m3.medium, m3.large, m3.xlarge, m3.2xlarge, m4.large,
      m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge, c4.large, c4.xlarge,
      c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge, c3.2xlarge,
      c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.
  ECSDesiredClusterSize:
    Description: Number of instances to launch in your ECS cluster.
    Type: Number
    Default: 1
  ECSMaxClusterSize:
    Description: Maximum number of instances that can be launched in your ECS cluster.
    Type: Number
    Default: 2
  ECSKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the ECS instances.
  # 03-create-jenkins-instance
  BastionInstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues: [t3.micro, t3.small, t3.medium, t3.large, t2.micro, t2.small,
      t2.medium, t2.large, m3.medium, m3.large, m3.xlarge, m3.2xlarge, m4.large,
      m4.xlarge, m4.2xlarge, m4.4xlarge, m4.10xlarge, c4.large, c4.xlarge,
      c4.2xlarge, c4.4xlarge, c4.8xlarge, c3.large, c3.xlarge, c3.2xlarge,
      c3.4xlarge, c3.8xlarge, r3.large, r3.xlarge, r3.2xlarge, r3.4xlarge,
      r3.8xlarge, i2.xlarge, i2.2xlarge, i2.4xlarge, i2.8xlarge]
    ConstraintDescription: Please choose a valid instance type.
  BastionRemoteAccessCIDR:
    Type: String
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/([0-9]|[1-2][0-9]|3[0-2]))$"
    Default: "0.0.0.0/0"
    Description: Allowed CIDR block for external SSH access to the bastions
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
  BastionKeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair to enable SSH access to the Bastion instance.
  DesiredNumBastionHosts:
    Description: Number of bastion hosts to launch at after start
    Type: Number
    Default: 1
  MaxNumBastionHosts:
    Description: Max number of bastion hosts to launch
    Type: Number
    Default: 1
  # 04-create-rds-instance
  DBName:
    Default: MyDatabase
    Description: The database name
    Type: String
    MinLength: '1'
    MaxLength: '64'
    Default: 'DBName'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBUser:
    Type: String
    Description: The database admin account username
    NoEcho: 'true'
    MinLength: '1'
    MaxLength: '16'
    Default: 'DBUser'
    AllowedPattern: '[a-zA-Z][a-zA-Z0-9]*'
    ConstraintDescription: must begin with a letter and contain only alphanumeric
      characters.
  DBPassword:
    Type: String
    Description: The database admin account password
    NoEcho: 'true'
    MinLength: '8'
    MaxLength: '41'
    Default: 'Qwerty123'
    AllowedPattern: '[a-zA-Z0-9]*'
    ConstraintDescription: must contain only alphanumeric characters.
  RDSGbStorage:
    Type: Number
    Default: '20'
    MinValue: '20'
    MaxValue: '1024'
    Description: The size of the database (Gb)
  DBInstanceClass:
    Type: String
    Default: db.t2.micro
    AllowedValues: [db.t1.micro, db.m1.small, db.m1.medium, db.m1.large, db.m1.xlarge,
      db.m2.xlarge, db.m2.2xlarge, db.m2.4xlarge, db.m3.medium, db.m3.large, db.m3.xlarge,
      db.m3.2xlarge, db.m4.large, db.m4.xlarge, db.m4.2xlarge, db.m4.4xlarge, db.m4.10xlarge,
      db.r3.large, db.r3.xlarge, db.r3.2xlarge, db.r3.4xlarge, db.r3.8xlarge, db.m2.xlarge,
      db.m2.2xlarge, db.m2.4xlarge, db.cr1.8xlarge, db.t2.micro, db.t2.small, db.t2.medium,
      db.t2.large]
    ConstraintDescription: must select a valid database instance type.
    Description: The database instance type
  RDSMultiAZ:
    Type: String
    Description: Multi-AZ master database
    Default: 'false'
    AllowedValues: ['true', 'false']
    ConstraintDescription: must be true or false.

Conditions:
  CreateRDS: !Equals [!Ref CreateRdsInstance, true]

Resources:
  ConfigVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR
      TemplateURL: https://s3-us-west-2.amazonaws.com/cfn-quickstart-templates/01-create-vpc.yaml
      TimeoutInMinutes: '5'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ConfigVPC
  ConfigECS:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        VpcCIDR: !Sub ${ConfigVPC.Outputs.VpcId}
        SubnetId: !Sub ${ConfigVPC.Outputs.PublicSubnets}
        InstanceType: !Ref ECSInstanceType
        DesiredClusterSize: !Ref ECSDesiredClusterSize
        MaxClusterSize: !Ref ECSMaxClusterSize
        KeyName: !Ref ECSKeyPair
        BastionSecurityGroupID: !Sub ${ConfigBastionHost.Outputs.BastionSecurityGroupID}
      TemplateURL: https://s3-us-west-2.amazonaws.com/cfn-quickstart-templates/02-create-ecs-cluster.yaml
      TimeoutInMinutes: '10'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ConfigECS
  ConfigBastionHost:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        VpcCIDR: !Sub ${ConfigVPC.Outputs.VpcId}
        SubnetId: !Sub ${ConfigVPC.Outputs.PublicSubnets}
        InstanceType: !Ref BastionInstanceType
        DesiredNumBastionHosts: !Ref DesiredNumBastionHosts
        MaxNumBastionHosts: !Ref MaxNumBastionHosts
        KeyName: !Ref BastionKeyPair
        RemoteAccessCIDR: !Ref BastionRemoteAccessCIDR
      TemplateURL: https://s3-us-west-2.amazonaws.com/cfn-quickstart-templates/03-create-bastion-instance.yaml
      TimeoutInMinutes: '15'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ConfigBastionHost
  ConfigRDS:
    Condition: CreateRDS
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
        VpcCIDR: !Sub ${ConfigVPC.Outputs.VpcId}
        SubnetId: !Sub ${ConfigVPC.Outputs.PrivateSubnets}
        DBName: !Ref DBName
        DBUser: !Ref DBUser
        DBPassword: !Ref DBPassword
        GbStorage: !Ref RDSGbStorage
        DBInstanceClass: !Ref DBInstanceClass
        EC2SecurityGroupID: !Sub ${ConfigECS.Outputs.ECSSecurityGroupID}
        MultiAZ: !Ref RDSMultiAZ
      TemplateURL: https://s3-us-west-2.amazonaws.com/cfn-quickstart-templates/04-create-rds-instance.yaml
      TimeoutInMinutes: '15'
      Tags:
        - Key: Name
          Value: !Sub ${AWS::StackName}-ConfigRDS

Outputs:
  VPC:
    Value: !Sub ${ConfigVPC.Outputs.VPC}
    Description: VPC name for environment
  PublicSubnets:
    Value: !Sub ${ConfigVPC.Outputs.PublicSubnets}
    Description: A list of the public subnets
  PrivateSubnets:
    Value: !Sub ${ConfigVPC.Outputs.PrivateSubnets}
    Description: A list of the private subnets