---
AWSTemplateFormatVersion: '2010-09-09'
Description: VPC setup

Parameters: 
  AppName: 
    Type: String
    Default: TestAppDev
    Description: Name of your application or organization
  VpcCidr: 
    Type: String
    Default: 10.0.0.0/24
    AllowedPattern: "^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\\/(\\d|[1-2]\\d|3[0-2]))?$"
    Description: Enter VPC IP in CIDR  x.x.x.x/y (x=1 to 255, y=1 to 32)

Resources:
  ConfigVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VpcCidr
      EnableDnsHostnames: true
      EnableDnsSupport: true
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-vpc

Outputs: 
  VPC:
    Value: !Ref VpcCidr
    Description: CIDR block of VPC
    Export:
      Name: !Sub ${AppName}-vpc