---
AWSTemplateFormatVersion: '2010-09-09'
Description: Provisioning environment
Parameters:
  AppName: 
    Type: String
    Default: TestApp
    Description: Name of your application or organization
Resources:
  CreateVPC:
    Type: AWS::CloudFormation::Stack
    Properties:
      Parameters:
        AppName: !Ref AppName
      TemplateURL: https://s3-us-west-2.amazonaws.com/cf-templates-f1qzfv4c2gms-us-west-2/create-vpc.yml
      TimeoutInMinutes: '1'
Outputs:
  VPC:
    Value: !Sub ${CreateVPC.Outputs.VPC}
    Description: VPC name for environment